# Generated by Django 6.0.5 on 2026-05-08 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='texto',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='reseña',
            name='calificacion',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reseña',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.juego'),
        ),
    ]
