# Generated by Django 6.0.5 on 2026-05-08 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_texto_reseña_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='reseña',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.reseña'),
        ),
    ]
